import { TechNode } from '../game/types';

export const TECHS: Record<string, TechNode> = {
  pottery: {
    id: 'pottery', name: 'Pottery', age: 'stone',
    cost: { industry: 10 }, requires: [], unlocksBuilding: 'granary',
  },
  hunting: {
    id: 'hunting', name: 'Hunting', age: 'stone',
    cost: { industry: 8 }, requires: [], runBonus: { damageMult: 0.10 },
  },
  mysticism: {
    id: 'mysticism', name: 'Mysticism', age: 'stone',
    cost: { culture: 10 }, requires: [], runBonus: { maxHp: 15 },
  },
  mining: {
    id: 'mining', name: 'Mining', age: 'stone',
    cost: { industry: 15, science: 5 }, requires: [], unlocksBuilding: 'mine',
  },
  writing: {
    id: 'writing', name: 'Writing', age: 'stone',
    cost: { science: 12 }, requires: [], runBonus: { draftChoices: 1 },
  },
  bronze_working: {
    id: 'bronze_working', name: 'Bronze Working', age: 'bronze',
    cost: { industry: 25, science: 20 }, requires: ['mining'],
    unlocksBuilding: 'forge', gatesAge: 'bronze',
  },
  iron_working: {
    id: 'iron_working', name: 'Iron Working', age: 'iron',
    cost: { industry: 40, science: 30 }, requires: ['bronze_working'],
    unlocksBuilding: 'smelter', gatesAge: 'iron',
  },
  deep_mining: {
    id: 'deep_mining', name: 'Deep Mining', age: 'iron',
    cost: { industry: 35 }, requires: ['iron_working'],
    unlocksBuilding: 'deep_mine',
  },
  smelting: {
    id: 'smelting', name: 'Smelting', age: 'iron',
    cost: { industry: 30, science: 30 }, requires: ['iron_working'],
    unlocksBuilding: 'foundry', runBonus: { weapons: ['flame_jet'] },
  },
  mechanics: {
    id: 'mechanics', name: 'Mechanics', age: 'iron',
    cost: { science: 45 }, requires: ['smelting'],
    runBonus: { weapons: ['sawblade'] },
  },
  mathematics: {
    id: 'mathematics', name: 'Mathematics', age: 'classical',
    cost: { science: 50, industry: 20 }, requires: ['iron_working'],
    unlocksBuilding: 'academy', gatesAge: 'classical',
  },
  currency: {
    id: 'currency', name: 'Currency', age: 'classical',
    cost: { industry: 30, exploration: 20 }, requires: ['mathematics'],
    unlocksBuilding: 'market',
  },
  engineering: {
    id: 'engineering', name: 'Engineering', age: 'classical',
    cost: { industry: 40, science: 25 }, requires: ['mathematics'],
    unlocksBuilding: 'workshop', runBonus: { weapons: ['ballista'] },
  },
  philosophy: {
    id: 'philosophy', name: 'Philosophy', age: 'classical',
    cost: { science: 35, culture: 20 }, requires: ['currency'],
    runBonus: { weapons: ['discus'] },
  },
  feudalism: { id: 'feudalism', name: 'Feudalism', age: 'medieval',
    cost: { industry: 60, science: 40 }, requires: ['engineering'],
    unlocksBuilding: 'keep', gatesAge: 'medieval' },
  masonry: { id: 'masonry', name: 'Masonry', age: 'medieval',
    cost: { industry: 45, science: 30 }, requires: ['feudalism'],
    unlocksBuilding: 'cathedral', runBonus: { maxHp: 20 } },
  chivalry: { id: 'chivalry', name: 'Chivalry', age: 'medieval',
    cost: { industry: 50, culture: 25 }, requires: ['feudalism'],
    unlocksBuilding: 'armory', runBonus: { weapons: ['crossbow'] } },
  guilds: { id: 'guilds', name: 'Guilds', age: 'medieval',
    cost: { industry: 40, exploration: 25 }, requires: ['masonry'], runBonus: { weapons: ['flail'] } },
  gunpowder: { id:'gunpowder', name:'Gunpowder', age:'renaissance',
    cost:{ industry:75, science:50 }, requires:['guilds'],
    unlocksBuilding:'gunsmith', gatesAge:'renaissance', runBonus:{ weapons:['musket'] } },
  printing_press: { id:'printing_press', name:'Printing Press', age:'renaissance',
    cost:{ science:60, culture:30 }, requires:['gunpowder'],
    unlocksBuilding:'university', runBonus:{ draftChoices:1 } },
  banking: { id:'banking', name:'Banking', age:'renaissance',
    cost:{ industry:50, exploration:35 }, requires:['gunpowder'], unlocksBuilding:'bank' },
  astronomy: { id:'astronomy', name:'Astronomy', age:'renaissance',
    cost:{ science:65 }, requires:['printing_press'], runBonus:{ weapons:['volley_pistols'] } },
  steam_power: { id:'steam_power', name:'Steam Power', age:'industrial',
    cost:{ industry:90, science:60 }, requires:['banking'],
    unlocksBuilding:'factory', gatesAge:'industrial', runBonus:{ weapons:['gatling'] } },
  railroad: { id:'railroad', name:'Railroad', age:'industrial',
    cost:{ industry:70, exploration:40 }, requires:['steam_power'], unlocksBuilding:'arsenal' },
  electricity: { id:'electricity', name:'Electricity', age:'industrial',
    cost:{ science:80, industry:50 }, requires:['steam_power'],
    unlocksBuilding:'powerplant', runBonus:{ weapons:['tesla_coil'] } },
  assembly_line: { id:'assembly_line', name:'Assembly Line', age:'industrial',
    cost:{ industry:75, science:45 }, requires:['railroad'], runBonus:{ draftChoices:1 } },
};
