import { BuildingDef } from '../game/types';

export const BUILDINGS: Record<string, BuildingDef> = {
  granary: {
    id: 'granary', name: 'Granary',
    baseCost: { industry: 10 },
    yield: { culture: 3 },
    runBonus: { maxHp: 25 },
    maxLevel: 3,
  },
  mine: {
    id: 'mine', name: 'Mine',
    baseCost: { industry: 15, science: 5 },
    yield: { industry: 4 },
    runBonus: { damageMult: 0.05 },
    maxLevel: 3,
  },
  forge: {
    id: 'forge', name: 'Forge',
    baseCost: { industry: 25, science: 15 },
    yield: { science: 3 },
    runBonus: { damageMult: 0.10, weapons: ['bronze_spear'] },
    maxLevel: 3,
  },
  smelter: {
    id: 'smelter', name: 'Smelter',
    baseCost: { industry: 40, science: 20 },
    yield: { industry: 5 },
    runBonus: { damageMult: 0.10, weapons: ['iron_pick'] },
    maxLevel: 3,
  },
  foundry: {
    id: 'foundry', name: 'Foundry',
    baseCost: { industry: 35, science: 35 },
    yield: { science: 5 },
    runBonus: { damageMult: 0.10, weapons: ['war_hammer'] },
    maxLevel: 3,
  },
  deep_mine: {
    id: 'deep_mine', name: 'Deep Mine',
    baseCost: { industry: 50, science: 15 },
    yield: { industry: 8 },
    runBonus: { damageMult: 0.08 },
    maxLevel: 3,
  },
  academy: {
    id: 'academy', name: 'Academy',
    baseCost: { science: 40, industry: 20 },
    yield: { science: 6 },
    runBonus: { draftChoices: 1, weapons: ['gladius'] },
    maxLevel: 3,
  },
  market: {
    id: 'market', name: 'Market',
    baseCost: { industry: 35, exploration: 15 },
    yield: { exploration: 5, culture: 3 },
    runBonus: { maxHp: 30 },
    maxLevel: 3,
  },
  workshop: {
    id: 'workshop', name: 'Workshop',
    baseCost: { industry: 45, science: 20 },
    yield: { industry: 7 },
    runBonus: { damageMult: 0.12, weapons: ['javelin'] },
    maxLevel: 3,
  },
  keep: { id: 'keep', name: 'Keep', baseCost: { industry: 60, science: 25 },
    yield: { industry: 9 }, runBonus: { maxHp: 40, weapons: ['longsword'] }, maxLevel: 3 },
  cathedral: { id: 'cathedral', name: 'Cathedral', baseCost: { culture: 40, science: 35 },
    yield: { culture: 6, science: 4 }, runBonus: { maxHp: 35 }, maxLevel: 3 },
  armory: { id: 'armory', name: 'Armory', baseCost: { industry: 55, science: 30 },
    yield: { industry: 8 }, runBonus: { damageMult: 0.14, weapons: ['halberd'] }, maxLevel: 3 },
};
